### ISSUE TITLE
请问qfluentwidgets是商用版吗？

### ISSUE THREAD

**Issue by muziyinlee** [LaoZhuJackson/auto_CoA#1]
运行程序后没有任何反应，py 3.12.1
![企业微信截图_20240106161729](https://github.com/LaoZhuJackson/auto_CoA/assets/94052636/801c84b0-31b0-4422-96bd-111318fb7368)

**Comment by LaoZhuJackson** [comment]
不是商用版，可能缺环境了，我上传一下requirements.txt

**Comment by LaoZhuJackson** [comment]
目前还没有打包软件，运行需要环境，如果想使用，可以等后续的打包好后的发行版

**Comment by muziyinlee** [comment]
我都安装了，这个是我pipreqs后的requirements.txt
loguru==0.7.2
Pillow==10.2.0
PyAutoGUI==0.9.54
PyGetWindow==0.0.9
PyQt5==5.15.10
PyQt5_sip==12.13.0
PyQt_Fluent_Widgets==1.4.5
PyScreeze==0.1.30

**Comment by muziyinlee** [comment]
没有任何报错，窗口也出来了！但是点击 开始 窗口就闪退了，就没有反应了！

**Comment by LaoZhuJackson** [comment]
用命令行窗口打开能看到报错：进入main文件夹->在该目录下打开cmd->输入“python main.py”->选择功能（刷体力还没写，你可以选个完成日常试试）->如果还闪退cmd会有报错信息

**Comment by muziyinlee** [comment]
报错信息，闪一下cmd就关闭了！

**Comment by LaoZhuJackson** [comment]
![image](https://github.com/LaoZhuJackson/auto_CoA/assets/56999771/782d3c7e-32d2-4e04-9077-0c5987c0cb54)
我尝试不打开游戏直接按开始是可以的，你选择的功能是什么

**Comment by muziyinlee** [comment]
完成日常！我知道了，我找到了！我看了下日志，是环境问题！少装了 一个环境opencv-python
loguru==0.7.2
Pillow==10.2.0
PyAutoGUI==0.9.54
PyGetWindow==0.0.9
PyQt5==5.15.10
PyQt5_sip==12.13.0
PyQt_Fluent_Widgets==1.4.5
PyScreeze==0.1.30
opencv-python==4.9.0.80

现在ok了，，感谢感谢，期待刷体力！这游戏，每天花时间太多，工作都落下了！刷体力要是出来了！省不少事情！！！
十分感谢！
